# Generated by Django 4.1.3 on 2022-11-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Productoxsede',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantDisponible', models.IntegerField()),
                ('cantReservada', models.IntegerField()),
                ('talla', models.CharField(max_length=5)),
                ('refProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acmeApp.producto')),
                ('refSede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acmeApp.sede')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acmeApp.sede')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
